name: Secret
on:
 workflow_dispatch:
 push:
    paths:
      - .github/workflows/02-secret.yml

jobs:
  echo-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Echo masked secret
        # Direct echo prints '***' in logs (masking)
        run: |
          echo "The secret is: ${{ secrets.MY_SECRET }}"
      - name: Use secret in env var
        env:
          SECRET_VAL: ${{ secrets.MY_SECRET }}
        run: |
          echo "Env secret also shows as: $SECRET_VAL"
