name: 03 - Manual environment choice with greetings

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Choose environment"
        type: choice
        options: [development, staging, production, test]
        default: development
      user_name:
        description: "Enter your name"
        type: string
        required: true
        default: "Guest"

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Show selected environment
        run: echo "Selected environment: ${{ inputs.target_env }}"
      
      - name: Display greeting
        run: echo "Welcome, ${{ inputs.user_name }} !!! ${{ env.greeting }} from ${{ inputs.target_env }}!!"
