name: Enviroment Variables

on:
 workflow_dispatch:
   inputs:
     target_env:
       description: "Choose Environment"
       type: choice
       options: [staging, Production, Test]
       default: Test
      user_name:
        description: "Enter your name"
        type: string
        required: true
        default: "Guest"
jobs:
  greet:
    runs-on: ubuntu-latest
    enviroment: ${{ inputs.target_env }}

    steps:
      - name: Show Selected Enviroment
        run: echo "Selected environmnet: ${{ inputs.target_env }}"

      - name: Display message
        run: |
           echo "Welcome, ${{ inputs.user_name }}"
           echo "${{vars.ENV_GREETING}} from ${{inputs.target_env}}"
